---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.8.1
    helm:
      releaseName: crossplane
      # See https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/values.yaml.tmpl
      values: |-
        provider:
          packages:
            - crossplane/provider-aws:master
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
