---
name: Main
on: 
  workflow_dispatch:
    inputs:
      PULUMI_STACK:
        required: true
        description: Stack to destroy
        type: string
jobs:
  pulumi_destroy:
    name: Pulumi Destroy
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Get AWS Region
        id: get_aws_region
        uses: mikefarah/yq@master
        with:
          cmd: yq '.config."aws:region"' "./aws/Pulumi.${{ inputs.PULUMI_STACK }}.yaml"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ steps.get_aws_region.outputs.result }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: rakiawspipeline
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install project dependencies
        working-directory: aws
        run: yarn install
      - name: Run Pulumi Destroy
        uses: pulumi/actions@v3
        with:
          command: destroy
          work-dir: ./aws
          stack-name: ${{ inputs.PULUMI_STACK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cloud-url: ${{ secrets.PULUMI_BACKEND_URL }}
          # secrets-provider:
          refresh: true
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
